/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2017-06-26 09:29:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"jQuery/jquery-1.11.3.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"form[name='f1']\").submit(function(){\r\n");
      out.write("\t\t\tif($.trim($(\":text[name='uname']\").val()).length==0){\r\n");
      out.write("\t\t\t\t$(\":text[name='uname']\").select();\r\n");
      out.write("\t\t\t\t$(\":text[name='uname']\").focus();\r\n");
      out.write("\t\t\t\t$(\"#info\").html(\"用户名不为空！\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif($.trim($(\":password[name='pwd']\").val()).length==0){\r\n");
      out.write("\t\t\t\t$(\":password[name='pwd']\").select();\r\n");
      out.write("\t\t\t\t$(\":password[name='pwd']\").focus();\r\n");
      out.write("\t\t\t\t$(\"#info\").html(\"密码不为空！\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar pwd=$(\":password[name='pwd']\").val();\r\n");
      out.write("\t\t\tvar pwd1=$(\":password[name='pwd1']\").val();\r\n");
      out.write("\t\t\tif(pwd!=pwd1){\r\n");
      out.write("\t\t\t\t$(\"#info\").html(\"两次输入的密码不一致！\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//至少选择一种爱好\r\n");
      out.write("\t\t\tvar times=0;\r\n");
      out.write("\t\t\t$(\":checkbox[name='hobby']\").each(function(i,e){\r\n");
      out.write("\t\t\t\tif(e.checked){\r\n");
      out.write("\t\t\t\t\ttimes++;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tif(times==0){\r\n");
      out.write("\t\t\t\t$(\"#info\").html(\"请至少选择一个爱好\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form name=\"f1\" action=\"show.jsp\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr><td>用户名</td><td><input type=\"text\" name=\"uname\"></td></tr>\r\n");
      out.write("\t\t<tr><td>密码</td><td><input type=\"password\" name=\"pwd\"></td></tr>\r\n");
      out.write("\t\t<tr><td>重复密码</td><td><input type=\"password\" name=\"pwd1\"></td></tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>所在省份</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<select name=\"prov\">\r\n");
      out.write("\t\t\t\t\t<option value=\"北京\">北京</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"上海\">上海</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"天津\">天津</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"重庆\">重庆</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>兴趣爱好</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"hobby\" value=\"爬山\">爬山\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"hobby\" value=\"上网\">上网\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"hobby\" value=\"看书\">看书\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"hobby\" value=\"下棋\">下棋\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"hobby\" value=\"游泳\">游泳\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"hobby\" value=\"乒乓球\">乒乓球\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\"><input type=\"submit\" value=\"提交信息\"><div id=\"info\"></div></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("</form>\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
